### ISSUE TITLE
大佬你可以PR到L大LEDE里不？

### ISSUE THREAD

**Issue by martin0607** [BROBIRD/openwrt-r8168#3]
RTL8111用此驱动目前正常使用没问题，希望可以PR到L大LEDE里去

**Comment by BROBIRD** [comment]
昨天更新到了8.048.03，你有空的话先试试看有没有问题

**Comment by martin0607** [comment]
昨天更新了下，目前为止还没有发现什么问题

**Comment by BROBIRD** [comment]
OK，我有空看看放到哪比较合适

**Comment by shikkoku** [comment]
🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。

**Comment by BROBIRD** [comment]
@shikkoku 有没有具体点的日志？

**Comment by shikkoku** [comment]
> @shikkoku 有没有具体点的日志？

没有截图了。因为我要用到UEFI引导，直接用了外国友人编译好的efi引导镜像了。19.07.3还没集成EFI引导生成选项的代码。Snapshot已经支持。

**Comment by BROBIRD** [comment]
> 
> 
> > @shikkoku 有没有具体点的日志？
> 
> 没有截图了。因为我要用到UEFI引导，直接用了外国友人编译好的efi引导镜像了。19.07.3还没集成EFI引导生成选项的代码。Snapshot已经支持。

没有日志不好定位啊，我没有什么好办法

**Comment by shikkoku** [comment]
> > > @shikkoku 有没有具体点的日志？
> > 
> > 
> > 没有截图了。因为我要用到UEFI引导，直接用了外国友人编译好的efi引导镜像了。19.07.3还没集成EFI引导生成选项的代码。Snapshot已经支持。
> 
> 没有日志不好定位啊，我没有什么好办法

🤔，那可以通过SDK来编译吗

**Comment by goldkeyber112** [comment]
> 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。

https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03

我还没测试，不过应该没问题

**Comment by shikkoku** [comment]
> > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> 
> https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> 
> @shikkoku 我还没测试，不过应该没问题

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
 * 	kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
 * opkg_install_cmd: Cannot install package kmod-r8168.

😂

**Comment by goldkeyber112** [comment]
> > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > 
> > 
> > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > @shikkoku 我还没测试，不过应该没问题
> 
> Collected errors:
> 
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> * opkg_install_cmd: Cannot install package kmod-r8168.
> 
> 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。

我的，我用的lean的，我找个sdk编译一下

**Comment by goldkeyber112** [comment]
> > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > 
> > 
> > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > @shikkoku 我还没测试，不过应该没问题
> 
> Collected errors:
> 
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> * opkg_install_cmd: Cannot install package kmod-r8168.
> 
> 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。

我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk

**Comment by shikkoku** [comment]
> > > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > > 
> > > 
> > > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > > @shikkoku 我还没测试，不过应该没问题
> > 
> > 
> > Collected errors:
> > 
> > * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> > * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> > * opkg_install_cmd: Cannot install package kmod-r8168.
> > 
> > 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。
> 
> 我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk

https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz

https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/

**Comment by goldkeyber112** [comment]
> > > > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > > > 
> > > > 
> > > > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > > > @shikkoku 我还没测试，不过应该没问题
> > > 
> > > 
> > > Collected errors:
> > > 
> > > * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> > > * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> > > * opkg_install_cmd: Cannot install package kmod-r8168.
> > > 
> > > 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。
> > 
> > 
> > 我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk
> 
> https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
> 
> https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/

为什么我就看不到呢，不好意思，好了文件已经上传你试一下

**Comment by shikkoku** [comment]
> > > > > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > > > > 
> > > > > 
> > > > > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > > > > @shikkoku 我还没测试，不过应该没问题
> > > > 
> > > > 
> > > > Collected errors:
> > > > 
> > > > * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> > > > * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> > > > * opkg_install_cmd: Cannot install package kmod-r8168.
> > > > 
> > > > 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。
> > > 
> > > 
> > > 我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk
> > 
> > 
> > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
> > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/
> 
> 为什么我就看不到呢，不好意思，好了文件已经上传你试一下

ethtool -i eth0
driver: r8168
version: 8.048.03-NAPI
firmware-version: 
expansion-rom-version: 
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no

正常装上了。有问题再更新，辛苦了。

**Comment by martin0607** [comment]
> > > > > > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > > > > > 
> > > > > > 
> > > > > > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > > > > > @shikkoku 我还没测试，不过应该没问题
> > > > > 
> > > > > 
> > > > > Collected errors:
> > > > > 
> > > > > * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> > > > > * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> > > > > * opkg_install_cmd: Cannot install package kmod-r8168.
> > > > > 
> > > > > 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。
> > > > 
> > > > 
> > > > 我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk
> > > 
> > > 
> > > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
> > > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/
> > 
> > 
> > 为什么我就看不到呢，不好意思，好了文件已经上传你试一下
> 
> ethtool -i eth0
> driver: r8168
> version: 8.048.03-NAPI
> firmware-version:
> expansion-rom-version:
> bus-info: 0000:02:00.0
> supports-statistics: yes
> supports-test: no
> supports-eeprom-access: no
> supports-register-dump: yes
> supports-priv-flags: no
> 
> 正常装上了。有问题再更新，辛苦了。
> 
> ethtool -k eth1
> Features for eth1:
> rx-checksumming: on
> tx-checksumming: on
> tx-checksum-ipv4: on
> tx-checksum-ip-generic: off [fixed]
> tx-checksum-ipv6: on
> tx-checksum-fcoe-crc: off [fixed]
> tx-checksum-sctp: off [fixed]
> scatter-gather: on
> tx-scatter-gather: on
> tx-scatter-gather-fraglist: off [fixed]
> tcp-segmentation-offload: on
> tx-tcp-segmentation: on
> tx-tcp-ecn-segmentation: off [fixed]
> tx-tcp-mangleid-segmentation: off
> tx-tcp6-segmentation: on
> generic-segmentation-offload: on
> generic-receive-offload: on
> large-receive-offload: off [fixed]
> rx-vlan-offload: on
> tx-vlan-offload: on
> ntuple-filters: off [fixed]
> receive-hashing: off [fixed]
> highdma: on [fixed]
> rx-vlan-filter: off [fixed]
> vlan-challenged: off [fixed]
> tx-lockless: off [fixed]
> netns-local: off [fixed]
> tx-gso-robust: off [fixed]
> tx-fcoe-segmentation: off [fixed]
> tx-gre-segmentation: off [fixed]
> tx-gre-csum-segmentation: off [fixed]
> tx-ipxip4-segmentation: off [fixed]
> tx-ipxip6-segmentation: off [fixed]
> tx-udp_tnl-segmentation: off [fixed]
> tx-udp_tnl-csum-segmentation: off [fixed]
> tx-gso-partial: off [fixed]
> tx-sctp-segmentation: off [fixed]
> tx-esp-segmentation: off [fixed]
> fcoe-mtu: off [fixed]
> tx-nocache-copy: off
> loopback: off [fixed]
> rx-fcs: off
> rx-all: off
> tx-vlan-stag-hw-insert: off [fixed]
> rx-vlan-stag-hw-parse: off [fixed]
> rx-vlan-stag-filter: off [fixed]
> l2-fwd-offload: off [fixed]
> hw-tc-offload: off [fixed]
> esp-hw-offload: off [fixed]
> esp-tx-csum-hw-offload: off [fixed]
> rx-udp_tunnel-port-offload: off [fixed]
> 
> 比起原来的驱动，这个驱动默认开启了TSO OFFLOAD和GSO OFFLOAD

才发现这个Firmware是空的，应该没影响吧？r8169倒是有Firmware编译出来了

**Comment by shikkoku** [comment]
> > > > > > > > 🤔能编译个给19.07.3的ipk包么。我这边编译过程老是报莫名其妙的错误。
> > > > > > > 
> > > > > > > 
> > > > > > > https://github.com/goldkeyber112/openwrt-r8168/releases/tag/8.048.03
> > > > > > > @shikkoku 我还没测试，不过应该没问题
> > > > > > 
> > > > > > 
> > > > > > Collected errors:
> > > > > > 
> > > > > > * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8168:
> > > > > > * kernel (= 4.19.122-1-342251a593166e03657c757eab3d49d3)
> > > > > > * opkg_install_cmd: Cannot install package kmod-r8168.
> > > > > > 
> > > > > > 😂官方的OPENWRT 19.07.3 X86_64平台还是4.14.180内核。
> > > > > 
> > > > > 
> > > > > 我在官方没找到19.07.3的的SDK只有17.07.2的。只重新编译了17.07.2的文件。没找到，如果你知道在哪，告诉我，或者你编译固件的时候可以生成sdk
> > > > 
> > > > 
> > > > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
> > > > https://downloads.openwrt.org/releases/19.07.3/targets/x86/64/
> > > 
> > > 
> > > 为什么我就看不到呢，不好意思，好了文件已经上传你试一下
> > 
> > 
> > ethtool -i eth0
> > driver: r8168
> > version: 8.048.03-NAPI
> > firmware-version:
> > expansion-rom-version:
> > bus-info: 0000:02:00.0
> > supports-statistics: yes
> > supports-test: no
> > supports-eeprom-access: no
> > supports-register-dump: yes
> > supports-priv-flags: no
> > 正常装上了。有问题再更新，辛苦了。
> > ethtool -k eth1
> > Features for eth1:
> > rx-checksumming: on
> > tx-checksumming: on
> > tx-checksum-ipv4: on
> > tx-checksum-ip-generic: off [fixed]
> > tx-checksum-ipv6: on
> > tx-checksum-fcoe-crc: off [fixed]
> > tx-checksum-sctp: off [fixed]
> > scatter-gather: on
> > tx-scatter-gather: on
> > tx-scatter-gather-fraglist: off [fixed]
> > tcp-segmentation-offload: on
> > tx-tcp-segmentation: on
> > tx-tcp-ecn-segmentation: off [fixed]
> > tx-tcp-mangleid-segmentation: off
> > tx-tcp6-segmentation: on
> > generic-segmentation-offload: on
> > generic-receive-offload: on
> > large-receive-offload: off [fixed]
> > rx-vlan-offload: on
> > tx-vlan-offload: on
> > ntuple-filters: off [fixed]
> > receive-hashing: off [fixed]
> > highdma: on [fixed]
> > rx-vlan-filter: off [fixed]
> > vlan-challenged: off [fixed]
> > tx-lockless: off [fixed]
> > netns-local: off [fixed]
> > tx-gso-robust: off [fixed]
> > tx-fcoe-segmentation: off [fixed]
> > tx-gre-segmentation: off [fixed]
> > tx-gre-csum-segmentation: off [fixed]
> > tx-ipxip4-segmentation: off [fixed]
> > tx-ipxip6-segmentation: off [fixed]
> > tx-udp_tnl-segmentation: off [fixed]
> > tx-udp_tnl-csum-segmentation: off [fixed]
> > tx-gso-partial: off [fixed]
> > tx-sctp-segmentation: off [fixed]
> > tx-esp-segmentation: off [fixed]
> > fcoe-mtu: off [fixed]
> > tx-nocache-copy: off
> > loopback: off [fixed]
> > rx-fcs: off
> > rx-all: off
> > tx-vlan-stag-hw-insert: off [fixed]
> > rx-vlan-stag-hw-parse: off [fixed]
> > rx-vlan-stag-filter: off [fixed]
> > l2-fwd-offload: off [fixed]
> > hw-tc-offload: off [fixed]
> > esp-hw-offload: off [fixed]
> > esp-tx-csum-hw-offload: off [fixed]
> > rx-udp_tunnel-port-offload: off [fixed]
> > 比起原来的驱动，这个驱动默认开启了TSO OFFLOAD和GSO OFFLOAD
> 
> 才发现这个Firmware是空的，应该没影响吧？r8169倒是有Firmware编译出来了

[   10.320219] r8168 Gigabit Ethernet driver 8.048.03-NAPI loaded
[   10.341302] r8168: This product is covered by one or more of the following patents: US6,570,884, US6,115,776, and US6,327,625.
[   10.355773] r8168  Copyright (C) 2020  Realtek NIC software team <nicfae@realtek.com> 
[   10.355773]  This program comes with ABSOLUTELY NO WARRANTY; for details, please see <http://www.gnu.org/licenses/>. 
[   10.355773]  This is free software, and you are welcome to redistribute it under certain conditions; see <http://www.gnu.org/licenses/>. 

下了一阵子BT,未出现掉线丢包问题。

**Comment by BROBIRD** [comment]
@martin0607 创建了PR https://github.com/coolsnowwolf/lede/pull/4835 ，感谢，此issue就先关闭了

**Comment by shikkoku** [comment]
> 
> 才发现这个Firmware是空的，应该没影响吧？r8169倒是有Firmware编译出来了

#6 最近这个更新加了firmware。
